# Generated by Django 5.0.3 on 2024-03-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F1ResultModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrandPix', models.CharField(max_length=30, verbose_name='GrandPix')),
                ('data', models.CharField(blank=True, max_length=30, null=True, verbose_name='data')),
                ('vencedor', models.CharField(blank=True, max_length=30, null=True, verbose_name='vencedor')),
                ('time', models.CharField(blank=True, max_length=30, verbose_name='time')),
                ('voltas', models.CharField(blank=True, max_length=30, verbose_name='voltas')),
            ],
        ),
    ]
