# Generated by Django 5.0.3 on 2024-03-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f1resultmodels',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='f1resultmodels',
            name='voltas',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='voltas'),
        ),
    ]
